# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Healthqt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studyqt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('healthScore', models.IntegerField()),
                ('studyScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('agreeNum', models.IntegerField()),
                ('disagreeNum', models.IntegerField()),
            ],
        ),
    ]
