# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three', '0003_users_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteid', models.IntegerField()),
                ('usename', models.CharField(max_length=32)),
                ('select', models.BooleanField()),
            ],
        ),
    ]
