# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('three', '0004_uservote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservote',
            old_name='usename',
            new_name='username',
        ),
    ]
