# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three', '0005_auto_20171216_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservote',
            name='select',
            field=models.IntegerField(),
        ),
    ]
